# Name of your workflow
name: My Test workflow

# Define the trigger events (s)
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:
    
    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, GibtHub Actions MK!"
